### ISSUE TITLE
still getting 39% accuracy, i am doing eval on "covidfl_pretrain_mae_base_split_checkpoint-1599.pth"

### ISSUE THREAD

**Issue by chillum-codeX** [rui-yan/SSL-FL#18]
still getting 39% accuracy, i am doing eval on "covidfl_pretrain_mae_base_central_checkpoint-1599.pth"
how will i reproduce the paper result do i need to fine tune on given weights or i am doing something wrong
dataset covidfl

++++++ Running Validation ++++++
Test:  [ 0/42]  eta: 0:03:35  loss: 1.0987 (1.0987)  acc1: 31.2500 (31.2500)  time: 5.1213  data: 3.1647  max mem: 1003
Test:  [10/42]  eta: 0:00:28  loss: 1.0987 (1.0987)  acc1: 31.2500 (32.0076)  time: 0.8942  data: 0.5685  max mem: 1003
Test:  [20/42]  eta: 0:00:19  loss: 1.0987 (1.0987)  acc1: 31.2500 (31.8948)  time: 0.6783  data: 0.5144  max mem: 1003
Test:  [30/42]  eta: 0:00:09  loss: 1.0987 (1.0987)  acc1: 32.2917 (32.5605)  time: 0.6996  data: 0.5351  max mem: 1003
Test:  [40/42]  eta: 0:00:01  loss: 1.0986 (1.0987)  acc1: 33.3333 (33.1047)  time: 0.6898  data: 0.5227  max mem: 1003
Test:  [41/42]  eta: 0:00:00  loss: 1.0986 (1.0987)  acc1: 33.3333 (32.9643)  time: 0.6857  data: 0.5227  max mem: 1003
Test: Total time: 0:00:32 (0.7767 s / it)
* Acc@1 32.964 loss 1.099
Accuracy of the network on the 3974 test images: 33.0%

command "python run_class_finetune_FedAvg.py --finetune /workspace/nvidia/pradeep/SSL-FL/output/covidfl_pretrain_mae_base_central_checkpoint-1599.pth --model vit_base_patch16 --output_dir /workspace/nvidia/pradeep/SSL-FL/OUTPUT_PATH_FT_mae/ --save_ckpt_freq 50 --batch_size 96 --warmup_epochs 5 --num_workers 4 --E_epoch 1 --log_dir /workspace/nvidia/pradeep/SSL-FL/log_dir/ --layer_decay 0.65 --weight_decay 0.05 --drop_path 0.1 --reprob 0.25 --mixup 0.8 --cutmix 1.0 --nb_classes 3 --eval --blr 3e-3 --n_clients 12 --num_local_clients -1 --split_type central --max_communication_rounds 100
"

iam doing --eval only to check pretrained model still getting low accuracy
do i need to fine tine on covidfl dataset

**Comment by rui-yan** [comment]
If you want to reproduce the results, as I've mentioned multiple times (e.g. in issue #16 and #17), please refer to the bash script [covidfl_central_ssl.sh](https://github.com/rui-yan/SSL-FL/blob/main/code/fed_mae/script/covidfl/covidfl_central_ssl.sh). 

In particular, please remove --eval in your command and add --max_communication_rounds {num_epochs_finetune} for fine-tuning. I could get an accuracy above 90% with num_epochs_finetune=1, and above 95% with num_epochs_finetune=5.

Yes, we do suggest you finetune for at least one epoch to get a good accuracy.

**Comment by chillum-codeX** [comment]
Ok let me work on it
Thanks sure i will

**Comment by chillum-codeX** [comment]
got 
* Acc@1 89.129 loss 0.371
Accuracy of the network on the 3974 validation images: 89.1%
Max accuracy: 89.13%

but another error
Max accuracy: 89.13%
Traceback (most recent call last):
  File "run_class_finetune_FedAvg.py", line 430, in <module>
    main(args, model)
  File "run_class_finetune_FedAvg.py", line 381, in main
    log_writer.update(test_acc1=test_stats['acc1'], head="perf", step=epoch)
AttributeError: 'SummaryWriter' object has no attribute 'update'

" let me see "

**Comment by rui-yan** [comment]
You need to update your torch version. You could also try ```from tensorboardX import SummaryWriter```, instead of ```from torch.utils.tensorboard import SummaryWriter``` in run_class_finetune_FedAvg.py, line 17.

**Comment by chillum-codeX** [comment]
Thanks
